# Generated by Django 5.2.1 on 2025-05-27 08:42

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True)),
                ('format', models.CharField(max_length=40)),
                ('profile', models.CharField(max_length=40)),
                ('material_corrugation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_material_corrugation', to='cardboard_production.material')),
                ('material_inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_material_inside', to='cardboard_production.material')),
                ('material_outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_material_outer', to='cardboard_production.material')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardboard_production.order')),
            ],
            options={
                'db_table': 'productions',
            },
        ),
    ]
