# Generated by Django 5.2.1 on 2025-06-03 21:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('format', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Формат, мм')),
            ],
            options={
                'verbose_name': 'Формат',
                'verbose_name_plural': 'Форматы',
                'db_table': 'format',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Материал слоя',
                'verbose_name_plural': 'Материалы слоев',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Наименование изделия')),
                ('profile', models.CharField(max_length=40, verbose_name='Профиль')),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_format', to='cardboard_production.format', verbose_name='Формат, мм')),
                ('material_corrugation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_material_corrugation', to='cardboard_production.material', verbose_name='Гофрирующий слой')),
                ('material_inside', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_material_inside', to='cardboard_production.material', verbose_name='Внутрений слой')),
                ('material_outer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_material_outer', to='cardboard_production.material', verbose_name='Наружный слой')),
            ],
            options={
                'verbose_name': 'Изделие',
                'verbose_name_plural': 'Изделия',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Productions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateField(verbose_name='Дата')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardboard_production.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Сменное задание',
                'verbose_name_plural': 'Сменные задания',
                'db_table': 'productions',
            },
        ),
    ]
