# Generated by Django 5.2.1 on 2025-06-03 21:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0002_profile_material_density_alter_material_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Density',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('density', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Плотность, г/м²')),
            ],
            options={
                'verbose_name': 'Плотность материала',
                'verbose_name_plural': 'Плотности материалов',
                'db_table': 'density',
            },
        ),
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_density', to='cardboard_production.density', verbose_name='Плотность, г/м²'),
        ),
    ]
