# Generated by Django 5.2.1 on 2025-06-17 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0004_productions_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='density',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Плотность, г/м²'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('name', 'density')},
        ),
    ]
