# Generated by Django 5.2.1 on 2025-06-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0006_delete_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='format',
        ),
        migrations.CreateModel(
            name='CuttingCardboard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_format', to='cardboard_production.format', verbose_name='Формат, мм')),
                ('order1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_1', to='cardboard_production.productions', verbose_name='Заказ')),
                ('order2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_2', to='cardboard_production.productions', verbose_name='Заказ')),
                ('order3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_3', to='cardboard_production.productions', verbose_name='Заказ')),
                ('order4', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_4', to='cardboard_production.productions', verbose_name='Заказ')),
                ('order5', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_5', to='cardboard_production.productions', verbose_name='Заказ')),
                ('order6', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_6', to='cardboard_production.productions', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Раскрой',
                'verbose_name_plural': 'Раскрой',
                'db_table': 'cutting_cardboard',
            },
        ),
    ]
