# Generated by Django 5.2.1 on 2025-06-23 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0009_alter_cuttingcardboard_order2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Scheme/%Y/%m/%d/', verbose_name='Cхема'),
        ),
        migrations.AddField(
            model_name='order',
            name='length',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Длина, мм'),
        ),
        migrations.AddField(
            model_name='order',
            name='width',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3000)], verbose_name='Ширина, мм'),
        ),
    ]
