# Generated by Django 5.2.1 on 2025-06-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0010_order_file_order_length_order_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Scheme/%Y/%m/', verbose_name='Cхема'),
        ),
    ]
