# Generated by Django 5.2.1 on 2025-06-24 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0011_alter_order_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuttingcardboard',
            name='order1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_1', to='cardboard_production.productions', verbose_name='Заказ 1'),
        ),
        migrations.AlterField(
            model_name='cuttingcardboard',
            name='order2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_2', to='cardboard_production.productions', verbose_name='Заказ 2'),
        ),
        migrations.AlterField(
            model_name='cuttingcardboard',
            name='order3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_3', to='cardboard_production.productions', verbose_name='Заказ 3'),
        ),
        migrations.AlterField(
            model_name='cuttingcardboard',
            name='order4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_4', to='cardboard_production.productions', verbose_name='Заказ 4'),
        ),
        migrations.AlterField(
            model_name='cuttingcardboard',
            name='order5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_5', to='cardboard_production.productions', verbose_name='Заказ 5'),
        ),
        migrations.AlterField(
            model_name='cuttingcardboard',
            name='order6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cutting_order_6', to='cardboard_production.productions', verbose_name='Заказ 6'),
        ),
    ]
