# Generated by Django 5.2.1 on 2025-07-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0013_alter_order_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.FloatField(default=0, verbose_name='Площадь м²'),
        ),
    ]
