# Generated by Django 5.2.1 on 2025-07-02 10:02

import cardboard_production.custom_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0014_order_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='Scheme/%Y/%m/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name='Файл')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='files',
            field=models.ManyToManyField(to='cardboard_production.feedfile'),
        ),
    ]
