# Generated by Django 5.2.1 on 2025-07-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0015_feedfile_order_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='files',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='cardboard_production.feedfile', verbose_name='Файлы'),
        ),
    ]
