# Generated by Django 5.2.1 on 2025-07-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0016_alter_order_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='files',
        ),
        migrations.DeleteModel(
            name='FeedFile',
        ),
    ]
