# Generated by Django 5.2.1 on 2025-07-14 05:30

import cardboard_production.custom_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0017_remove_order_files_delete_feedfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='design_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Design/%Y/%m/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name='Дизайн'),
        ),
        migrations.AddField(
            model_name='order',
            name='equipment_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Equipment/%Y/%m/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name='Комплектация'),
        ),
    ]
