# Generated by Django 5.2.1 on 2025-07-16 10:08

import cardboard_production.custom_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0018_order_design_file_order_equipment_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='file2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Scheme2/%Y/%m/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name='Чертёж 2'),
        ),
        migrations.AddField(
            model_name='order',
            name='set_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Площадь комплекта м²'),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Scheme/%Y/%m/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name='Чертёж 1'),
        ),
    ]
