# Generated by Django 5.2.1 on 2025-07-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0020_alter_order_design_file_alter_order_equipment_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='color_count',
            field=models.IntegerField(choices=[(0, '-'), (1, '1'), (2, '2'), (3, '3')], default=0, verbose_name='Печать'),
        ),
        migrations.AddField(
            model_name='order',
            name='stamp',
            field=models.BooleanField(choices=[(False, '-'), (True, '+')], default=False, verbose_name='Штамп'),
        ),
    ]
