# Generated by Django 5.2.1 on 2025-07-29 10:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0021_order_color_count_order_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('statement_date', models.DateField(verbose_name='Дата')),
                ('statement_start_time', models.TimeField(verbose_name='Начало')),
                ('statement_end_time', models.TimeField(verbose_name='Окончание')),
                ('downtime', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Простой, мин')),
                ('quantity_sent_production', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Пропущено')),
                ('quantity_manufactured', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Изготовлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardboard_production.order', verbose_name='Продукция')),
            ],
            options={
                'verbose_name': 'Ведомость',
                'verbose_name_plural': 'Ведомости',
                'db_table': 'statement',
            },
        ),
    ]
