# Generated by Django 5.2.1 on 2025-07-29 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0022_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_order', to='cardboard_production.order', verbose_name='Продукция'),
        ),
    ]
