# Generated by Django 5.2.1 on 2025-08-12 07:12

import cardboard_production.custom_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0023_alter_statement_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='design_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Design/%Y/%m/%d/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='equipment_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Equipment/%Y/%m/%d/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Scheme/%Y/%m/%d/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='file2',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Scheme2/%Y/%m/%d/', validators=[cardboard_production.custom_validator.custom_file_validator], verbose_name=''),
        ),
    ]
