# Generated by Django 5.2.1 on 2026-01-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0024_alter_order_design_file_alter_order_equipment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Наименование изделия'),
        ),
    ]
