# Generated by Django 5.2.1 on 2026-01-26 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0025_alter_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area_one_product',
            field=models.FloatField(default=0, verbose_name='Площадь 1 изделия м²'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity_products_per_stamp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Кол-во изделий на штампе'),
        ),
    ]
