# Generated by Django 5.2.1 on 2026-01-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0026_order_area_one_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='area_one_product',
        ),
    ]
