# Generated by Django 5.2.1 on 2026-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0027_remove_order_area_one_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='area',
            field=models.FloatField(default=0, verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='order',
            name='set_area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Площадь комплекта, м²'),
        ),
    ]
