# Generated by Django 5.2.1 on 2026-04-06 12:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0028_alter_order_area_alter_order_set_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElectroCounters',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(default=100, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Номер счетчика')),
                ('client_name', models.CharField(max_length=40, unique=True, verbose_name='Наименование клиента')),
                ('address', models.IntegerField(default=100, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Сетевой адрес')),
                ('transformation_coefficient', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэф. трансформации')),
            ],
            options={
                'verbose_name': 'Электросчетчик',
                'verbose_name_plural': 'Электросчетчики',
                'db_table': 'electro_counters',
            },
        ),
    ]
