# Generated by Django 5.2.1 on 2026-04-11 04:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0029_electrocounters'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrocounters',
            name='energy',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер счетчика'),
        ),
    ]
