# Generated by Django 5.2.1 on 2026-04-11 05:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0030_electrocounters_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electrocounters',
            name='energy',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение энергии'),
        ),
    ]
