# Generated by Django 5.2.1 on 2026-04-22 07:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0031_alter_electrocounters_energy'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrocounters',
            name='energy_indic',
            field=models.BigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение эн. на счетчике'),
        ),
        migrations.AlterField(
            model_name='electrocounters',
            name='address',
            field=models.IntegerField(default=100, unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)], verbose_name='Сетевой адрес регистра'),
        ),
    ]
