# Generated by Django 5.2.1 on 2026-06-29 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0032_electrocounters_energy_indic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'В очереди'), (1, 'В производстве'), (2, 'Печатать накладную')], default=0, verbose_name='Накладная'),
        ),
    ]
