# Generated by Django 5.2.1 on 2026-06-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardboard_production', '0033_statement_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Нет'), (2, 'Печатать накладную')], default=0, verbose_name='Накладная'),
        ),
    ]
